package com.jl.arky.jfinal.app.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseMxZwgkNews<M extends BaseMxZwgkNews<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public void setCatid(java.lang.Integer catid) {
		set("catid", catid);
	}

	public java.lang.Integer getCatid() {
		return get("catid");
	}

	public void setTypeid(java.lang.Integer typeid) {
		set("typeid", typeid);
	}

	public java.lang.Integer getTypeid() {
		return get("typeid");
	}

	public void setTitle(java.lang.String title) {
		set("title", title);
	}

	public java.lang.String getTitle() {
		return get("title");
	}

	public void setStyle(java.lang.String style) {
		set("style", style);
	}

	public java.lang.String getStyle() {
		return get("style");
	}

	public void setThumb(java.lang.String thumb) {
		set("thumb", thumb);
	}

	public java.lang.String getThumb() {
		return get("thumb");
	}

	public void setKeywords(java.lang.String keywords) {
		set("keywords", keywords);
	}

	public java.lang.String getKeywords() {
		return get("keywords");
	}

	public void setDescription(java.lang.String description) {
		set("description", description);
	}

	public java.lang.String getDescription() {
		return get("description");
	}

	public void setPosids(java.lang.Boolean posids) {
		set("posids", posids);
	}

	public java.lang.Boolean getPosids() {
		return get("posids");
	}

	public void setUrl(java.lang.String url) {
		set("url", url);
	}

	public java.lang.String getUrl() {
		return get("url");
	}

	public void setListorder(java.lang.Integer listorder) {
		set("listorder", listorder);
	}

	public java.lang.Integer getListorder() {
		return get("listorder");
	}

	public void setStatus(java.lang.Integer status) {
		set("status", status);
	}

	public java.lang.Integer getStatus() {
		return get("status");
	}

	public void setSysadd(java.lang.Boolean sysadd) {
		set("sysadd", sysadd);
	}

	public java.lang.Boolean getSysadd() {
		return get("sysadd");
	}

	public void setIslink(java.lang.Boolean islink) {
		set("islink", islink);
	}

	public java.lang.Boolean getIslink() {
		return get("islink");
	}

	public void setUsername(java.lang.String username) {
		set("username", username);
	}

	public java.lang.String getUsername() {
		return get("username");
	}

	public void setInputtime(java.lang.Long inputtime) {
		set("inputtime", inputtime);
	}

	public java.lang.Long getInputtime() {
		return get("inputtime");
	}

	public void setUpdatetime(java.lang.Long updatetime) {
		set("updatetime", updatetime);
	}

	public java.lang.Long getUpdatetime() {
		return get("updatetime");
	}

	public void setStitle(java.lang.String stitle) {
		set("stitle", stitle);
	}

	public java.lang.String getStitle() {
		return get("stitle");
	}

	public void setWjh(java.lang.String wjh) {
		set("wjh", wjh);
	}

	public java.lang.String getWjh() {
		return get("wjh");
	}

}
