package com.jl.arky.jfinal.app.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseCarousel<M extends BaseCarousel<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public void setLink(java.lang.String link) {
		set("link", link);
	}

	public java.lang.String getLink() {
		return get("link");
	}

	public void setSortid(java.lang.Integer sortid) {
		set("sortid", sortid);
	}

	public java.lang.Integer getSortid() {
		return get("sortid");
	}

	public void setTitle(java.lang.String title) {
		set("title", title);
	}

	public java.lang.String getTitle() {
		return get("title");
	}

	public void setTolink(java.lang.String tolink) {
		set("tolink", tolink);
	}

	public java.lang.String getTolink() {
		return get("tolink");
	}

	public void setCarouselType(java.lang.Integer carouselType) {
		set("carouselType", carouselType);
	}

	public java.lang.Integer getCarouselType() {
		return get("carouselType");
	}

}
