package com.jl.arky.jfinal.app.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseMxCategory<M extends BaseMxCategory<M>> extends Model<M> implements IBean {

	public void setCatid(java.lang.Integer catid) {
		set("catid", catid);
	}

	public java.lang.Integer getCatid() {
		return get("catid");
	}

	public void setSiteid(java.lang.Integer siteid) {
		set("siteid", siteid);
	}

	public java.lang.Integer getSiteid() {
		return get("siteid");
	}

	public void setModule(java.lang.String module) {
		set("module", module);
	}

	public java.lang.String getModule() {
		return get("module");
	}

	public void setType(java.lang.Boolean type) {
		set("type", type);
	}

	public java.lang.Boolean getType() {
		return get("type");
	}

	public void setModelid(java.lang.Integer modelid) {
		set("modelid", modelid);
	}

	public java.lang.Integer getModelid() {
		return get("modelid");
	}

	public void setParentid(java.lang.Integer parentid) {
		set("parentid", parentid);
	}

	public java.lang.Integer getParentid() {
		return get("parentid");
	}

	public void setArrparentid(java.lang.String arrparentid) {
		set("arrparentid", arrparentid);
	}

	public java.lang.String getArrparentid() {
		return get("arrparentid");
	}

	public void setChild(java.lang.Boolean child) {
		set("child", child);
	}

	public java.lang.Boolean getChild() {
		return get("child");
	}

	public void setArrchildid(java.lang.String arrchildid) {
		set("arrchildid", arrchildid);
	}

	public java.lang.String getArrchildid() {
		return get("arrchildid");
	}

	public void setCatname(java.lang.String catname) {
		set("catname", catname);
	}

	public java.lang.String getCatname() {
		return get("catname");
	}

	public void setStyle(java.lang.String style) {
		set("style", style);
	}

	public java.lang.String getStyle() {
		return get("style");
	}

	public void setImage(java.lang.String image) {
		set("image", image);
	}

	public java.lang.String getImage() {
		return get("image");
	}

	public void setDescription(java.lang.String description) {
		set("description", description);
	}

	public java.lang.String getDescription() {
		return get("description");
	}

	public void setParentdir(java.lang.String parentdir) {
		set("parentdir", parentdir);
	}

	public java.lang.String getParentdir() {
		return get("parentdir");
	}

	public void setCatdir(java.lang.String catdir) {
		set("catdir", catdir);
	}

	public java.lang.String getCatdir() {
		return get("catdir");
	}

	public void setUrl(java.lang.String url) {
		set("url", url);
	}

	public java.lang.String getUrl() {
		return get("url");
	}

	public void setItems(java.lang.Integer items) {
		set("items", items);
	}

	public java.lang.Integer getItems() {
		return get("items");
	}

	public void setHits(java.lang.Long hits) {
		set("hits", hits);
	}

	public java.lang.Long getHits() {
		return get("hits");
	}

	public void setSetting(java.lang.String setting) {
		set("setting", setting);
	}

	public java.lang.String getSetting() {
		return get("setting");
	}

	public void setListorder(java.lang.Integer listorder) {
		set("listorder", listorder);
	}

	public java.lang.Integer getListorder() {
		return get("listorder");
	}

	public void setIsmenu(java.lang.Boolean ismenu) {
		set("ismenu", ismenu);
	}

	public java.lang.Boolean getIsmenu() {
		return get("ismenu");
	}

	public void setSethtml(java.lang.Boolean sethtml) {
		set("sethtml", sethtml);
	}

	public java.lang.Boolean getSethtml() {
		return get("sethtml");
	}

	public void setLetter(java.lang.String letter) {
		set("letter", letter);
	}

	public java.lang.String getLetter() {
		return get("letter");
	}

	public void setUsableType(java.lang.String usableType) {
		set("usable_type", usableType);
	}

	public java.lang.String getUsableType() {
		return get("usable_type");
	}

}
