package com.jl.arky.jfinal.app.model;

import com.jfinal.plugin.activerecord.ActiveRecordPlugin;

/**
 * Generated by JFinal, do not modify this file.
 * <pre>
 * Example:
 * public void configPlugin(Plugins me) {
 *     ActiveRecordPlugin arp = new ActiveRecordPlugin(...);
 *     _MappingKit.mapping(arp);
 *     me.add(arp);
 * }
 * </pre>
 */
public class _MappingKit {

	public static void mapping(ActiveRecordPlugin arp) {
/*		arp.addMapping("admin", "id", Admin.class);
		arp.addMapping("admin_log", "id", AdminLog.class);
		arp.addMapping("admin_role", "id", AdminRole.class);
		arp.addMapping("carousel", "id", Carousel.class);
		arp.addMapping("channel", "id", Channel.class);
		arp.addMapping("email", "id", Email.class);
		arp.addMapping("letter", "id", Letter.class);
		arp.addMapping("letter_dept", "id", LetterDept.class);
		arp.addMapping("letter_type", "id", LetterType.class);
		arp.addMapping("mx_category", "catid", MxCategory.class);
		arp.addMapping("mx_zwgk_news", "id", MxZwgkNews.class);
		arp.addMapping("navigation", "id", Navigation.class);
		arp.addMapping("news", "id", News.class);
		arp.addMapping("privilege", "id", Privilege.class);
		arp.addMapping("role", "id", Role.class);
		arp.addMapping("role_privilege", "id", RolePrivilege.class);
		arp.addMapping("rss_channel", "id", RssChannel.class);
		arp.addMapping("rss_items", "id", RssItems.class);
		arp.addMapping("schedule", "id", Schedule.class);*/
	}
}

