package com.jl.arky.jfinal.app.model;

import com.jl.arky.jfinal.app.model.base.BaseAdmin;


/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Admin extends BaseAdmin<Admin> {
	public static final Admin dao = new Admin();
}
