package com.jl.arky.jfinal.app.model;

import com.jl.arky.jfinal.app.model.base.BaseAdminRole;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class AdminRole extends BaseAdminRole<AdminRole> {
	public static final AdminRole dao = new AdminRole();
}
