package com.jl.arky.jfinal.app.model;

import com.jl.arky.jfinal.app.model.base.BaseAdminLog;


/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class AdminLog extends BaseAdminLog<AdminLog> {
	public static final AdminLog dao = new AdminLog();
}
