package com.jl.arky.jfinal.app.model;

import com.jl.arky.jfinal.app.model.base.BaseCarousel;


/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Carousel extends BaseCarousel<Carousel> {
	public static final Carousel dao = new Carousel();
}
