package com.jl.arky.jfinal.app.model;

import com.jl.arky.jfinal.app.model.base.BaseChannel;


/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Channel extends BaseChannel<Channel> {
	public static final Channel dao = new Channel();
	
	public boolean hasChild() {
		return Channel.dao.find("select * from channel where pid=?",get("id")).size()==0?false:true;
		}
}
