package com.jl.arky.jfinal.app.model;

import com.jl.arky.jfinal.app.model.base.BaseEmail;


/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Email extends BaseEmail<Email> {
	public static final Email dao = new Email();
}
