package com.jl.arky.jfinal.app.model;

import com.jl.arky.jfinal.app.model.base.BaseLetter;


/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Letter extends BaseLetter<Letter> {
	public static final Letter dao = new Letter();
}
