package com.jl.arky.jfinal.app.model;

import com.jl.arky.jfinal.app.model.base.BaseLetterType;


/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class LetterType extends BaseLetterType<LetterType> {
	public static final LetterType dao = new LetterType();
}
