package com.jl.arky.jfinal.app.model;

import com.jl.arky.jfinal.app.model.base.BaseLetterDept;


/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class LetterDept extends BaseLetterDept<LetterDept> {
	public static final LetterDept dao = new LetterDept();
}
