package com.jl.arky.jfinal.app.model;

import com.jl.arky.jfinal.app.model.base.BaseMxCategory;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class MxCategory extends BaseMxCategory<MxCategory> {
	public static final MxCategory dao = new MxCategory();
}
