package com.jl.arky.jfinal.app.model;

import com.jl.arky.jfinal.app.model.base.BaseMxZwgkNews;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class MxZwgkNews extends BaseMxZwgkNews<MxZwgkNews> {
	public static final MxZwgkNews dao = new MxZwgkNews();
}
