package com.jl.arky.jfinal.app.model;

import com.jl.arky.jfinal.app.model.base.BaseNavigation;


/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Navigation extends BaseNavigation<Navigation> {
	public static final Navigation dao = new Navigation();
}
