package com.jl.arky.jfinal.app.model;

import com.jl.arky.jfinal.app.model.base.BaseNews;


/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class News extends BaseNews<News> {
	public static final News dao = new News();
}
