package com.jl.arky.jfinal.app.model;

import com.jl.arky.jfinal.app.model.base.BasePrivilege;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Privilege extends BasePrivilege<Privilege> {
	public static final Privilege dao = new Privilege();
}
