package com.jl.arky.jfinal.app.model;

import com.jl.arky.jfinal.app.model.base.BaseRolePrivilege;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class RolePrivilege extends BaseRolePrivilege<RolePrivilege> {
	public static final RolePrivilege dao = new RolePrivilege();
}
