package com.jl.arky.jfinal.app.model;

import com.jl.arky.jfinal.app.model.base.BaseRole;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Role extends BaseRole<Role> {
	public static final Role dao = new Role();
}
