package com.jl.arky.jfinal.app.model;

import com.jl.arky.jfinal.app.model.base.BaseRssChannel;


/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class RssChannel extends BaseRssChannel<RssChannel> {
	public static final RssChannel dao = new RssChannel();
}
