package com.jl.arky.jfinal.app.model;

import com.jl.arky.jfinal.app.model.base.BaseRssItems;


/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class RssItems extends BaseRssItems<RssItems> {
	public static final RssItems dao = new RssItems();
}
