package com.jl.arky.jfinal.app.model;

import com.jl.arky.jfinal.app.model.base.BaseSchedule;


/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Schedule extends BaseSchedule<Schedule> {
	public static final Schedule dao = new Schedule();
}
